version: '1.0'
services:
  db_postgres:
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=romashkako'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'
    volumes:
      - '/var/lib/postgresql/data'