spring:
  application:
    name: RomashkaKO
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/romashkako
    username: postgres
    password: postgres
  liquibase:
    change-log: db.changelog/main-changelog.xml
