spring:
  application:
    name: RomashkaKO
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/romashkako
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db.changelog/main-changelog.xml
